# Generated by Django 2.2 on 2021-04-13 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlco_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transportation_invoice',
            old_name='venodor',
            new_name='vendor',
        ),
    ]
