# Generated by Django 2.2 on 2021-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlco_app', '0002_auto_20210413_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='note',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
